#single asset with CRRA 
# max number of ticks
maxT=191999
#record time
recordTime=168000

# number of assets present on market 
numAssets=1

# Name of file describing classes and number of instances of agents to be used in simulation 
agentConfiguration=chsw.txt

# name of class of orderbook to use
orderBookClass=DoubleAuctionOrderBook

# options for orderbook (only used for DoubleAuctionOrderBooks)
orderBookOptions=logPricing

#Initial price
initialPrice=100.0

# agent have initialPositon So, and initial cash equal to So*Po .
initialPosition=50


#drift of common value
mu=0

#volatility of common value between two periods
sigma1=0.6

#volatility of common value between two periods
sigma2=0.3

#volatility of common value between two periods
sigman=0.1

#volatility of common value between two periods
sigmae=0.05

#Impatient trader orders placed per step
lambda=1

# the parameter of the chartist belief
gc=0.6

# initial risk aversion
alph=0.1

# 
phi=0.0

# order size
quantity=1
# use log of prices in the OrderBook (and in the graphs); 
# uses log prices internally regardless. 
# If true, must set orderBookOption to "logPricing"
logPricing=false
# granularity for limit pricing (only for non-log pricing).
# 0.0 == Continuous, 100.0 == trading on cents
granularity=100

# maximum investing time horizon  
tau=480

# tauf
tauf = 240

#  time of one day  
T=480

# k 
k = 600

# displayTime
displayTime = 10
